# "2731181579", # Wild Mountains Livonia Veg, breaks CUP skyboxes

name = "SWS Addons"
author = "Maid"
prefix = "SWS"
mainprefix = "x"

[properties]
author = "Maid"
url = "https://github.com/WitchFreya/SWSAddons"

[hemtt.launch.default]
workshop = [
    "1572627279", # optre first contact
    "1659590037", # fireteam zulu - required by 19th
    "1797512739", # operation arsenal expansion for OPTRE
    "1858075458", # LAMBS_Danger
    "2016312756", # opcan
    "2047587607", # 19th fleet armor mod
    "2261045061", # TCGM
    "2369477168", # advanced developer tools
    "2522638637", # ace arsenal extended
    "3007731986", # SWS Timeless
    "450814997",  # cba_a3
    "463939057",  # ace
    "623475643",  # 3den Enhanced
    "769440155",  # OPTRE
    "894678801",  # TFAR
    "2018593688", # Zeus Enhanced - ACE3 Compatibilityr
    "583496184",  # CUP Terrains - Core
    "861133494",  # JSRS SOUNDMOD
    "2695649037", # Operation TREBUCHET JSRS Compat
    "1763651451", # optre PLUS+
    "333310405",  # Enhanced Movement
    "2034363662", # Enhanced Movement Rework
    "561177050",  # Mission Enhanced Little Bird

    # patches
    "1779063631", # zen
    "1790880882", # 41st odst/mfr declassified
    "2359395889", # TCGM_Divinities_2.0
    "2480118782", # Max Women Soldiers
    "2699465073", # Fire Support Plus
    "2909265898", # OPTRE Ordnance Expansion
    "520618345",  # Jbad
    "2515887728", # Crow's EWAR

    # unnecessary but i want them there
    "1957746437", # ADV ACE-CPR
    # "620260972",  # ALiVE
]

[hemtt.launch.full]
workshop = [
    "1224892496", # gruppe adler trenches
    "1251859358", # Zeus and Eden Interiors
    "1572627279", # optre first contact
    "1638341685", # dui squad radar
    "1659590037", # fireteam zulu
    "1677267612", # ace medical assistant
    "1763651451", # optre PLUS+
    "1767731032", # HEV patch
    "1779063631", # zeus enhanced
    "1790880882", # 41st odst/mfr declassified
    "1858075458", # LAMBS_Danger
    "1876589191", # JM's Structures
    "1957746437", # ADV ACE-CPR
    "2016312756", # opcan
    "2018593688", # Zeus Enhanced - ACE3 Compatibility
    "2034363662", # Enhanced Movement Rework
    "2041057379", # A3 Thermal Improvement
    "2047587607", # 19th fleet armor mod
    "2198339170", # Alternative Running
    "2261045061", # tcgm
    "2359395889", # TCGM_Divinities_2.0
    "2359977960", # ZEPHIK Female Units V2
    "2361950567", # Operation TREBUCHET Zephik Females Compat
    "2480118782", # Max Women Soldiers
    "2522638637", # ace arsenal extended
    "2538444208", # Simple Grid Designators
    "2695649037", # Operation TREBUCHET JSRS Compat
    "2699465073", # Fire Support Plus
    "2735613231", # Weather Plus
    "2794721649", # Advanced Vault System: Remastered
    "2822758266", # Deformer
    "2853202785", # Freefall Fix
    "2918542818", # Sci-fi Support Plus
    "3007731986", # SWS Timeless
    "333310405",  # Enhanced Movement
    "450814997",  # cba
    "463939057",  # ace
    "520618345",  # Jbad
    "583496184",  # CUP Terrains - Core
    "583544987",  # CUP Terrains - Maps
    "623475643",  # 3den Enhanced
    "767380317",  # Blastcore Edited (standalone version)
    "769440155",  # optre
    "837729515",  # CH View Distance
    "861133494",  # JSRS SOUNDMOD
    "894678801",  # tfar
    "925018569",  # WMO - Walkable Moving Objects
    # mods I hate
    "1797512739", # operation arsenal expansion for OPTRE
    "2909265898", # OPTRE Ordnance Expansion

    # v2 mods
    "2617713656", # Halo Music Collection
    "2969350304", # Ladder Tweak Remastered
    "1770265310", # No More Aircraft Bouncing
    "1911374016", # ACE Vehicle Medical

    # v3 mods
    "2291129343", # Improved Melee System
    "2933180786", # WebKnight's OPTRE Expansion
    "1910457930", # Fapovo Island
    "1960024802", # PLP All In One

    # v6 mods
    "561177050", # Mission Enhanced Little Bird

    # v7 mods
    "2515887728", # Crow's EWAR
    "2993442344", # Death & Hit Reactions
    "2447965207", # Crow's Zeus Additions

    # additional mods
    "2791403093", # Better Inventory
    "2467590475", # Enhanced Map Ace Version
    "1623498241", # turret enhanced
    "2013446344", # Simple MapTools
    "2369477168", # advanced developer tools
]

[hemtt.launch.ai]
workshop = [
    "1224892496", # gruppe adler trenches
    "1251859358", # Zeus and Eden Interiors
    "1572627279", # optre first contact
    "1638341685", # dui squad radar
    "1659590037", # fireteam zulu
    "1677267612", # ace medical assistant
    "1763651451", # optre PLUS+
    "1767731032", # HEV patch
    "1779063631", # zeus enhanced
    "1790880882", # 41st odst/mfr declassified
    "1808238502", # lambs suppression
    "1858075458", # LAMBS_Danger
    "1876589191", # JM's Structures
    "1957746437", # ADV ACE-CPR
    "2016312756", # opcan
    "2018593688", # Zeus Enhanced - ACE3 Compatibility
    "2034363662", # Enhanced Movement Rework
    "2041057379", # A3 Thermal Improvement
    "2047587607", # 19th fleet armor mod
    "2198339170", # Alternative Running
    "2261045061", # tcgm
    "2359395889", # TCGM_Divinities_2.0
    "2359977960", # ZEPHIK Female Units V2
    "2361950567", # Operation TREBUCHET Zephik Females Compat
    "2480118782", # Max Women Soldiers
    "2522638637", # 'aceax_ingame' - ace arsenal extended
    "2538444208", # Simple Grid Designators
    "2695649037", # Operation TREBUCHET JSRS Compat
    "2699465073", # Fire Support Plus
    "2918542818", # Sci-fi Support Plus
    "3007731986", # SWS Timeless
    "333310405",  # Enhanced Movement
    "450814997",  # cba
    "463939057",  # ace
    "520618345",  # Jbad
    "583544987",  # CUP Terrains - Maps
    "623475643",  # 3den Enhanced
    "767380317",  # Blastcore Edited (standalone version)
    "769440155",  # optre
    "837729515",  # CH View Distance
    "861133494",  # JSRS SOUNDMOD
    "894678801",  # tfar
    "925018569",  # WMO - Walkable Moving Objects

    # "2731181579", # Wild Mountains Livonia Veg

    "2735613231", # Weather Plus
    "2794721649", # Advanced Vault System: Remastered
    "2822758266", # Deformer
    "2853202785", # Freefall Fix


    "583496184", # CUP Terrains - Core

    # mods I hate
    "1797512739", # operation arsenal expansion for OPTRE
    "2909265898", # OPTRE Ordnance Expansion

    # v2 mods
    "2617713656", # Halo Music Collection
    "2969350304", # Ladder Tweak Remastered
    "1770265310", # No More Aircraft Bouncing
    "1911374016", # ACE Vehicle Medical

    # v3 mods
    "2291129343", # Improved Melee System
    "2933180786", # WebKnight's OPTRE Expansion
    "1910457930", # Fapovo Island
    "1960024802", # PLP All In One

    # v6 mods
    "561177050", # Mission Enhanced Little Bird

    # v7 mods
    "2515887728", # Crow's EWAR
    "2993442344", # Death & Hit Reactions
    "2447965207", # Crow's Zeus Additions

    # additional mods
    "2791403093", # Better Inventory
    "2467590475", # Enhanced Map Ace Version
    "1623498241", # turret enhanced
    "2013446344", # Simple MapTools
    "2369477168", # advanced developer tools
]

[hemtt.release]
archive = false

[files]
exclude = ["*.inc"]
