name = "SWS Addons"
author = "Maid"
prefix = "sws"
mainprefix = "x"

[properties]
author = "Maid"
url = "https://github.com/WitchFreya/SWSAddons"

[files]
exclude = ["*.inc"]

# To use this profile, copy .hemtt/missions/Dev.VR.Template to .hemtt/missions/Dev.VR and edit that to your heart's content
[hemtt.launch.vr]
mission = "Dev.VR"

[hemtt.launch.default]
workshop = [
  "1224892496", # gruppe adler trenches
  "1572627279", # optre first contact
  "1659590037", # fireteam zulu - required by 19th
  "1797512739", # operation arsenal expansion for OPTRE
  "1858075458", # LAMBS_Danger
  "2016312756", # opcan
  "2261045061", # TCGM
  "2369477168", # advanced developer tools
  "3007731986", # SWS Timeless
  "450814997",  # cba_a3
  "463939057",  # ace
  "623475643",  # 3den Enhanced
  "769440155",  # OPTRE
  "583496184",  # CUP Terrains - Core
  "1763651451", # optre PLUS+
  "333310405",  # Enhanced Movement
  "2034363662", # Enhanced Movement Rework
  "561177050",  # Mission Enhanced Little Bird
  "751965892", # acre
  # v9 mods
  "3038821437", # UNSC Foundries
  "3038826897", # UNSC Foundries ACE compat

  # v11 mods
  "3055061422", # Evolved Role Progression
  "2522638637", # ace arsenal extended

  # v13
  "2202413047", # ACE No Uniform Restriction

  # patches
  "1779063631", # zen
  "2291129343", # improved melee system (dependency of 41st)
  "1790880882", # 41st odst/mfr declassified
  "2359395889", # TCGM_Divinities_2.0
  "2480118782", # Max Women Soldiers
  "2699465073", # Fire Support Plus
  "520618345",  # Jbad
  "2515887728", # Crow's EWAR
  "2918542818", # Sci-fi Support Plus
  "2447965207", # Crow's Zeus Additions
  "925018569",  # WMO - Walkable Moving Objects

  # server mods
  "1768992669", # inidb2
]

[hemtt.launch.full]
workshop = [
  "1224892496", # gruppe adler trenches
  "1251859358", # Zeus and Eden Interiors
  "1572627279", # optre first contact
  "1638341685", # dui squad radar
  "1659590037", # fireteam zulu
  "1677267612", # ace medical assistant
  "1763651451", # optre PLUS+
  "1767731032", # HEV patch
  "1779063631", # zeus enhanced
  "1790880882", # 41st odst/mfr declassified
  "1858075458", # LAMBS_Danger
  "1876589191", # JM's Structures
  "2016312756", # opcan
  "2034363662", # Enhanced Movement Rework
  "2041057379", # A3 Thermal Improvement
  "2198339170", # Alternative Running
  "2261045061", # tcgm
  "2359395889", # TCGM_Divinities_2.0
  "2359977960", # ZEPHIK Female Units V2
  "2361950567", # Operation TREBUCHET Zephik Females Compat
  "2480118782", # Max Women Soldiers
  "2538444208", # Simple Grid Designators
  "2699465073", # Fire Support Plus
  "2735613231", # Weather Plus
  "2794721649", # Advanced Vault System: Remastered
  "2822758266", # Deformer
  "2853202785", # Freefall Fix
  "2918542818", # Sci-fi Support Plus
  "3007731986", # SWS Timeless
  "333310405",  # Enhanced Movement
  "450814997",  # cba
  "463939057",  # ace
  "520618345",  # Jbad
  "583496184",  # CUP Terrains - Core
  "583544987",  # CUP Terrains - Maps
  "623475643",  # 3den Enhanced
  "767380317",  # Blastcore Edited (standalone version)
  "769440155",  # optre
  "837729515",  # CH View Distance
  "925018569",  # WMO - Walkable Moving Objects
  "1797512739", # operation arsenal expansion for OPTRE
  "751965892", # acre

  # v2 mods
  "2617713656", # Halo Music Collection
  "2969350304", # Ladder Tweak Remastered
  "1770265310", # No More Aircraft Bouncing
  "1911374016", # ACE Vehicle Medical

  # v3 mods
  "2291129343", # Improved Melee System
  "2933180786", # WebKnight's OPTRE Expansion
  "1910457930", # Fapovo Island
  "1960024802", # PLP All In One

  # v6 mods
  "561177050", # Mission Enhanced Little Bird

  # v7 mods
  "2515887728", # Crow's EWAR
  "2993442344", # Death & Hit Reactions
  "2447965207", # Crow's Zeus Additions

  # v9 mods
  "3038821437", # UNSC Foundries
  "3038826897", # UNSC Foundries ACE compat

  # v11 mods
  "3055061422", # Evolved Role Progression
  "2522638637", # ace arsenal extended

  # v12 mods
  "2796579441", # OPTRE precursors

  # v13
  "2202413047", # ACE No Uniform Restriction

  # v14 mods
  "2387989178", # FM Target & Barricade Pack

  # v15
  "2917444360", # Global Ops Terrains
  "2499317133", # Space Skyboxes
  "1508091616", # Metis Marker
  # "1957746437", # ADV ACE-CPR (removed in this version)

  # additional mods
  "2791403093", # Better Inventory
  "1623498241", # turret enhanced
  "2013446344", # Simple MapTools
  "2369477168", # advanced developer tools

  # server mods
  "1768992669", # inidb2
]

[hemtt.launch.deletion]
workshop = [
  # Base
  "450814997",  # cba
  "463939057",  # ace
  "2202413047", # ACE No Uniform Restriction

  # Ours
  "3007731986", # SWS Timeless
  "3055061422", # Evolved Role Progression
  "1768992669", # inidb2 - ERP requirement

  # Tools - Architect/Dev
  "2369477168", # advanced developer tools
  "623475643",  # 3den Enhanced
  "1779063631", # zeus enhanced
  "2822758266", # Deformer
  "2447965207", # Crow's Zeus Additions

  # Weapons, Armor, Units, Content
  "769440155",  # optre
  "1572627279", # optre first contact
  "1763651451", # optre PLUS+
  "1659590037", # fireteam zulu
  "1790880882", # 41st odst/mfr declassified
  "2016312756", # opcan
  "2933180786", # WebKnight's OPTRE Expansion
  "3038821437", # UNSC Foundries
  "2796579441", # OPTRE precursors
  "2515887728", # Crow's EWAR
  "2261045061", # tcgm
  "2359395889", # TCGM_Divinities_2.0
  "2480118782", # Max Women Soldiers
  "2359977960", # ZEPHIK Female Units V2
  "561177050",  # Mission Enhanced Little Bird

  # Locations and Structures/Decorations
  "1876589191", # JM's Structures
  "1251859358", # Zeus and Eden Interiors
  "520618345",  # Jbad
  "1960024802", # PLP All In One
  "2917444360", # Global Ops Terrains
  "583496184",  # CUP Terrains - Core
  "583544987",  # CUP Terrains - Maps
  "2499317133", # Space Skyboxes
  "2387989178", # FM Target & Barricade Pack

  # QoL - Server/GM
  "1858075458", # LAMBS_Danger
  "767380317",  # Blastcore Edited (standalone version)
  "2617713656", # Halo Music Collection
  "1770265310", # No More Aircraft Bouncing
  "2853202785", # Freefall Fix
  "1767731032", # HEV patch
  "2993442344", # Death & Hit Reactions

  # Movement
  "925018569",  # WMO - Walkable Moving Objects
  "2794721649", # Advanced Vault System: Remastered
  "333310405",  # Enhanced Movement
  "2034363662", # Enhanced Movement Rework
  "2198339170", # Alternative Running
  "2291129343", # Improved Melee System

  # QoL - Player
  "1224892496", # gruppe adler trenches
  "1638341685", # dui squad radar
  "1677267612", # ace medical assistant
  "2041057379", # A3 Thermal Improvement
  "837729515",  # CH View Distance
  "2538444208", # Simple Grid Designators
  "2969350304", # Ladder Tweak Remastered
  "894678801",  # tfar
  "1911374016", # ACE Vehicle Medical
  "2522638637", # ace arsenal extended
  "1508091616", # Metis Marker
  "2791403093", # Better Inventory
  "2013446344", # Simple MapTools
  "1623498241", # turret enhanced

  # Compats
  "3038826897", # UNSC Foundries ACE compat
  "2361950567", # Operation TREBUCHET Zephik Females Compat

  # removal candidates
  # "2918542818", # Sci-fi Support Plus
  # "2699465073", # Fire Support Plus
  # "1797512739", # operation arsenal expansion for OPTRE
  "2735613231", # Weather Plus
]

[hemtt.launch.jsrs]
workshop = [
  "861133494",  # JSRS SOUNDMOD
  "2695649037", # Operation TREBUCHET JSRS Compat
]

[hemtt.launch.dynasound]
workshop = [
  "825179978", # enhanced soundscape
  "825181638", # dynasound 2
  "2874616322", # OPTRE dynasound 2 compat
]

[hemtt.launch.alive]
workshop = [
  "620260972", # ALiVE
]
